"""Golden-parity tests: the port must reproduce the reference implementation.

The fixture JSONs were generated by the original (private) implementation of the
index on six StatsBomb OPEN-data matches — including a 3-3 final, two shootout
quarterfinals, a dull 0-0, a 7-0 rout, and the France 4-3 Argentina 2018
classic. Every measure this package computes must match those values (including
which measures come out NaN). Event data is fetched from the open-data repo on
first run and cached; tests skip gracefully when offline with no cache.
"""
from __future__ import annotations

import glob
import json
import math
import os
from pathlib import Path

import pandas as pd
import pytest

FIXTURE_DIR = Path(__file__).parent / "fixtures"
os.environ.setdefault("EXCITEMENT_INDEX_CACHE",
                      str(Path(__file__).parent.parent / ".opendata_cache"))

# fixture stage strings (open-data competition_stage names, lower-cased)
STAGES = {3869685: "final", 3869321: "quarter-finals", 3869420: "quarter-finals",
          3857265: "group stage", 3857291: "group stage", 7580: "round of 16"}

# Columns in the fixtures that are metadata or unscored private-side extras the
# public package intentionally does not compute.
SKIP_KEYS = {"match_id", "slug", "qualification_jeopardy",
             "gei_late_weighted", "take_on_volume", "missed_chance_leverage",
             "obv_volatility", "went_to_et_pens", "live_suspense", "live_closeness",
             "leverage_saves", "postshot_xg_minus_goals", "stage_depth",
             "shootout_drama_scaled", "receptions_between_lines", "table_stakes",
             "shootout", "pressure_volume", "switches_crosses", "xg_race_closeness",
             "home", "away", "stage", "match_date"}


def _fixtures():
    return [p for p in sorted(glob.glob(str(FIXTURE_DIR / "*.json")))
            if not p.endswith("wc2022_board.json")]


def _load_events_or_skip(match_id):
    from excitement_index import opendata
    try:
        return opendata.load_events(match_id)
    except Exception as e:  # offline and uncached
        pytest.skip(f"open data unavailable ({e})")


@pytest.mark.parametrize("path", _fixtures(), ids=lambda p: Path(p).stem)
def test_measure_parity(path):
    from excitement_index import extract_features, opendata

    fx = json.load(open(path))
    ev = _load_events_or_skip(fx["match_id"])
    sh, sa = (int(x) for x in fx["score"].split("-"))
    row = pd.Series({"home": fx["home"], "away": fx["away"],
                     "score_home": sh, "score_away": sa,
                     "stage": STAGES[fx["match_id"]]})
    got = extract_features(ev, row, elo=opendata.load_elo())

    mismatches = []
    for name, want in fx["features"].items():
        if name in SKIP_KEYS or name not in got:
            continue
        g = got[name]
        if want is None:
            if not (g is None or (isinstance(g, float) and math.isnan(g))):
                mismatches.append(f"{name}: expected NaN, got {g}")
        else:
            if g is None or (isinstance(g, float) and math.isnan(g)):
                mismatches.append(f"{name}: expected {want}, got NaN")
            elif abs(float(g) - float(want)) > 1e-6 * max(1.0, abs(float(want))):
                mismatches.append(f"{name}: got {g!r}, want {want!r}")
    assert not mismatches, f"{Path(path).stem}: {len(mismatches)} mismatches\n" + "\n".join(mismatches)


def test_all_taxonomy_measures_are_registered():
    """Every measure the shipped config scores must exist in the registry."""
    from excitement_index import load_config
    from excitement_index.measures.registry import registered_measures

    cfg = load_config()
    registry = registered_measures()
    missing = [m for feats in cfg["taxonomy"].values() for m in feats if m not in registry]
    assert not missing, f"taxonomy names unregistered measures: {missing}"


@pytest.mark.skipif(not os.environ.get("RUN_SLOW"), reason="set RUN_SLOW=1 for the full-tournament test")
def test_wc2022_board_end_to_end():
    """The whole 2022 World Cup, end to end, against the reference board
    (raw scores and the resulting ranking). Slow: fetches and processes all 64
    matches (~10 min cold)."""
    from excitement_index import build_feature_matrix, opendata, score_matches

    oracle = json.load(open(FIXTURE_DIR / "wc2022_board.json"))
    matches = opendata.load_matches("FIFA World Cup", "2022")
    fm = build_feature_matrix(matches, opendata.load_events,
                              elo=opendata.load_elo(), jeopardy=False)
    grp = [b["match_id"] for b in oracle["board"] if b["stage"] == "group"]
    board = score_matches(fm, reference_ids=grp, floor=oracle["floor_m"])
    want = {b["match_id"]: b for b in oracle["board"]}
    for mid, b in want.items():
        assert abs(board.loc[mid, "raw"] - b["raw"]) < 5e-4, \
            f"{b['home']}-{b['away']}: raw {board.loc[mid, 'raw']:.4f} vs oracle {b['raw']:.4f}"
    got_order = list(board.index)
    want_order = [b["match_id"] for b in oracle["board"]]
    assert got_order[:10] == want_order[:10], "top-10 ordering diverged from the oracle"
    assert got_order[0] == 3869685, "Argentina-France 2022 must rank #1"
